// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:12c1ba14d3b1f6ee8b9f742b5003063525bb4648d28ea7dfed54d36e42371922",
    "semanticFingerprint": "typebox-value-hash-v1:c239a47b9932bbb9",
    "defaultSettings": {
        "enabled": true,
        "initialNaming": {
            "enabled": true,
            "timing": "prompt",
            "trigger": "messages",
            "threshold": 1
        },
        "refreshNaming": {
            "enabled": false,
            "trigger": "turns",
            "threshold": 10
        },
        "model": "current",
        "reasoningEffort": "low",
        "timeoutMs": 30000,
        "conversationScope": "minimized",
        "prompt": "Generate a title that will help the user recognize this coding session weeks later.\n\nBefore answering, silently identify:\n- Subject: the system, feature, or problem the request is really about.\n- Outcome: what the user ultimately wants to understand or change.\n- Incidental instructions: details about tools, process, output, or how the agent should work.\n\nTitle the durable subject and desired outcome. Discard incidental instructions.\nPrioritize user requests over assistant discoveries. Preserve the original subject until the user clearly changes goals.\n\nEditorial rules:\n- Use 3 to 8 words and a compact noun phrase or clear action phrase.\n- Capture the umbrella goal when the request lists several symptoms or steps.\n- Name the product change, not a plan, report, branch, commit, PR, test run, or monitoring step used to produce it.\n- Exclude models, subagents, tools, and output formats unless they are themselves the topic.\n- For reviews, name what is being reviewed and the relevant concern.\n- For research, name the question domain rather than the research process.\n- Do not claim the work is complete or merely copy and truncate the request.\n- Avoid repository names already visible in the workspace metadata, quotes, labels, filler, and trailing punctuation.\n\nWorkspace metadata:\n<workspace>\n{{repository_context}}\n</workspace>\n\nConversation:\n<conversation>\n{{conversation}}\n</conversation>\n\nCurrent title: {{current_name}}\nNaming phase: {{reason}}",
        "nameConstraints": {
            "minLength": 6,
            "maxLength": 40
        }
    }
} as const;

export default artifact;
